[package]
name = "my_awesome_game"
version = "0.1.0"
authors = ["Dusten Sobotta <dusten@hey.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
gdnative = "0.9.3"
# gdnative = { path = "../../godot-rust/gdnative" }
